import React, { useState } from 'react';
import { useTheme } from '../contexts/ThemeContext2';
import { 
  FileText, 
  Download, 
  Calendar,
  Filter,
  Search,
  ChevronDown,
  Eye,
  Edit,
  Trash2,
  Plus,
  BarChart3,
  TrendingUp,
  Users,
  DollarSign,
  FileDown,
  RefreshCw,
  CheckCircle,
  AlertCircle,
  Clock
} from 'lucide-react';

const Reports = () => {
  const { theme } = useTheme();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPeriod, setSelectedPeriod] = useState('30days');
  const [selectedReport, setSelectedReport] = useState('all');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [notification, setNotification] = useState(null);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setNotification({ type: 'info', message: 'Generating report...' });
    
    // Simulate report generation
    setTimeout(() => {
      const newReport = {
        id: reports.length + 1,
        title: `${selectedReport === 'all' ? 'General' : selectedReport.charAt(0).toUpperCase() + selectedReport.slice(1)} Report - ${new Date().toLocaleDateString()}`,
        type: selectedReport === 'all' ? 'general' : selectedReport,
        date: new Date().toISOString().split('T')[0],
        status: 'completed',
        generatedBy: 'Current User',
        size: '2.1 MB',
        downloads: 0
      };
      
      setReports([newReport, ...reports]);
      setIsGenerating(false);
      setNotification({ type: 'success', message: 'Report generated successfully!' });
      
      // Clear notification after 3 seconds
      setTimeout(() => setNotification(null), 3000);
    }, 2000);
  };

  const handleExportAll = () => {
    setIsExporting(true);
    setNotification({ type: 'info', message: 'Exporting all reports...' });
    
    // Simulate export process
    setTimeout(() => {
      const filteredReports = getFilteredReports();
      // Create CSV data
      const csvContent = filteredReports.map(report => 
        `${report.title},${report.type},${report.date},${report.status},${report.generatedBy},${report.size},${report.downloads}`
      ).join('\n');
      
      // Create and download file
      const blob = new Blob([`Report Name,Type,Date,Status,Generated By,Size,Downloads\n${csvContent}`], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `reports-export-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
      // Update download counts for all exported reports
      setReports(reports.map(report => 
        filteredReports.find(fr => fr.id === report.id) 
          ? { ...report, downloads: report.downloads + 1 }
          : report
      ));
      
      setIsExporting(false);
      setNotification({ type: 'success', message: 'Reports exported successfully!' });
      
      // Clear notification after 3 seconds
      setTimeout(() => setNotification(null), 3000);
    }, 1500);
  };

  const handleExportSingle = (report) => {
    setNotification({ type: 'info', message: `Exporting ${report.title}...` });
    
    setTimeout(() => {
      const csvContent = `${report.title},${report.type},${report.date},${report.status},${report.generatedBy},${report.size},${report.downloads}`;
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${report.title.replace(/\s+/g, '-').toLowerCase()}-${report.date}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
      // Update download count for the exported report
      setReports(reports.map(r => 
        r.id === report.id 
          ? { ...r, downloads: r.downloads + 1 }
          : r
      ));
      
      setNotification({ type: 'success', message: 'Report exported successfully!' });
      setTimeout(() => setNotification(null), 3000);
    }, 1000);
  };

  const getFilteredReports = () => {
    let filtered = reports;
    
    // Apply report type filter
    if (selectedReport !== 'all') {
      filtered = filtered.filter(report => report.type === selectedReport);
    }
    
    // Apply period filter
    const now = new Date();
    let cutoffDate;
    
    switch (selectedPeriod) {
      case '7days':
        cutoffDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        break;
      case '30days':
        cutoffDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
        break;
      case '90days':
        cutoffDate = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
        break;
      case 'year':
        cutoffDate = new Date(now.getFullYear(), 0, 1);
        break;
      default:
        cutoffDate = null;
    }
    
    if (cutoffDate) {
      filtered = filtered.filter(report => new Date(report.date) >= cutoffDate);
    }
    
    // Apply search filter
    if (searchQuery.trim()) {
      filtered = filtered.filter(report => 
        report.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        report.type.toLowerCase().includes(searchQuery.toLowerCase()) ||
        report.generatedBy.toLowerCase().includes(searchQuery.toLowerCase()) ||
        report.status.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }
    
    return filtered;
  };

  const [reports, setReports] = useState([
    {
      id: 1,
      title: 'User Activity Report',
      type: 'user-activity',
      date: '2024-03-10',
      status: 'completed',
      generatedBy: 'Admin',
      size: '2.4 MB',
      downloads: 45
    },
    {
      id: 2,
      title: 'Security Audit Report',
      type: 'security',
      date: '2024-03-09',
      status: 'completed',
      generatedBy: 'System',
      size: '1.8 MB',
      downloads: 23
    },
    {
      id: 3,
      title: 'Performance Metrics Report',
      type: 'performance',
      date: '2024-03-08',
      status: 'processing',
      generatedBy: 'Admin',
      size: '3.1 MB',
      downloads: 12
    },
    {
      id: 4,
      title: 'Admin Access Log',
      type: 'access',
      date: '2024-03-07',
      status: 'completed',
      generatedBy: 'System',
      size: '1.2 MB',
      downloads: 67
    },
    {
      id: 5,
      title: 'System Health Report',
      type: 'health',
      date: '2024-03-05',
      status: 'completed',
      generatedBy: 'System',
      size: '2.7 MB',
      downloads: 34
    }
  ]);

  const filteredReports = getFilteredReports();

  const reportStats = [
    {
      title: 'Total Reports',
      value: filteredReports.length.toString(),
      change: '+12%',
      icon: <FileText className="h-6 w-6" />,
      color: 'bg-blue-100 text-blue-600 dark:bg-blue-900/20 dark:text-blue-400'
    },
    {
      title: 'This Month',
      value: filteredReports.filter(r => new Date(r.date) >= new Date(new Date().getFullYear(), new Date().getMonth(), 1)).length.toString(),
      change: '+8%',
      icon: <Calendar className="h-6 w-6" />,
      color: 'bg-green-100 text-green-600 dark:bg-green-900/20 dark:text-green-400'
    },
    {
      title: 'Downloads',
      value: filteredReports.reduce((sum, r) => sum + r.downloads, 0).toString(),
      change: '+18%',
      icon: <Download className="h-6 w-6" />,
      color: 'bg-purple-100 text-purple-600 dark:bg-purple-900/20 dark:text-purple-400'
    },
    {
      title: 'Active Users',
      value: '89',
      change: '+5%',
      icon: <Users className="h-6 w-6" />,
      color: 'bg-orange-100 text-orange-600 dark:bg-orange-900/20 dark:text-orange-400'
    }
  ];

  const getStatusColor = (status) => {
    switch (status) {
      case 'completed':
        return 'bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-300';
      case 'processing':
        return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-300';
      case 'failed':
        return 'bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-300';
      default:
        return 'bg-gray-100 text-gray-800 dark:bg-gray-900/20 dark:text-gray-300';
    }
  };

  const getReportTypeIcon = (type) => {
    switch (type) {
      case 'user-activity':
        return <Users className="h-5 w-5 text-blue-500" />;
      case 'security':
        return <BarChart3 className="h-5 w-5 text-red-500" />;
      case 'performance':
        return <TrendingUp className="h-5 w-5 text-green-500" />;
      case 'access':
        return <FileText className="h-5 w-5 text-purple-500" />;
      case 'health':
        return <BarChart3 className="h-5 w-5 text-orange-500" />;
      default:
        return <FileText className="h-5 w-5 text-gray-500" />;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 w-full">
      <div className="w-full max-w-full px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Reports</h1>
          <p className="text-gray-600 dark:text-gray-400">Generate and manage system reports and analytics.</p>
        </div>

        {/* Stats Cards */}
        <div className="grid gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 mb-8">
          {reportStats.map((stat, index) => (
            <div key={index} className="card p-6 transition-all hover:shadow-lg w-full">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-400">{stat.title}</p>
                  <p className="mt-2 text-3xl font-bold text-gray-900 dark:text-white">{stat.value}</p>
                  <div className="mt-2 flex items-center gap-1">
                    <span className={`text-sm font-medium ${
                      stat.change.startsWith('+') ? 'text-green-600' : 'text-red-600'
                    }`}>{stat.change}</span>
                    <span className="text-sm text-gray-500">from last month</span>
                  </div>
                </div>
                <div className={`rounded-lg p-3 ${stat.color}`}>
                  {stat.icon}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Filters and Actions */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 p-6 mb-8">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center flex-wrap">
              {/* Search */}
              <div className="relative flex-shrink-0">
                <Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search reports..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg  dark:border-gray-600 dark:bg-gray-700 dark:text-white w-64"
                />
              </div>

              {/* Period Filter */}
              <div className="relative flex-shrink-0">
                <select
                  value={selectedPeriod}
                  onChange={(e) => setSelectedPeriod(e.target.value)}
                  className="appearance-none pl-10 pr-10 py-2 border border-gray-300 rounded-lg dark:border-gray-600 dark:bg-gray-700 dark:text-white w-50"
                >
                  <option value="7days">Last 7 Days</option>
                  <option value="30days">Last 30 Days</option>
                  <option value="90days">Last 90 Days</option>
                  <option value="year">Last Year</option>
                </select>
                <Calendar className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400 pointer-events-none" />
                <ChevronDown className="absolute right-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400 pointer-events-none" />
              </div>

              {/* Report Type Filter */}
              <div className="relative flex-shrink-0">
                <select
                  value={selectedReport}
                  onChange={(e) => setSelectedReport(e.target.value)}
                  className="appearance-none pl-10 pr-10 py-2 border border-gray-300 rounded-lg  focus:border-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white w-50"
                >
                  <option value="all">All Reports</option>
                  <option value="user-activity">User Activity</option>
                  <option value="security">Security</option>
                  <option value="performance">Performance</option>
                  <option value="access">Access Logs</option>
                </select>
                <Filter className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400 pointer-events-none" />
                <ChevronDown className="absolute right-3 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400 pointer-events-none" />
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3 flex-shrink-0">
              <button 
                onClick={handleGenerateReport}
                disabled={isGenerating}
                className={`flex items-center gap-2 px-6 py-3 rounded-lg font-medium transition-all duration-200 ${
                  isGenerating 
                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed dark:bg-gray-600 dark:text-gray-400' 
                    : 'bg-gradient-to-r from-blue-600 to-blue-700 text-white hover:from-blue-700 hover:to-blue-800 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5'
                }`}
              >
                {isGenerating ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Plus className="h-4 w-4" />
                    Generate Report
                  </>
                )}
              </button>
              
              <button 
                onClick={handleExportAll}
                disabled={isExporting}
                className={`flex items-center gap-2 px-6 py-3 rounded-lg font-medium transition-all duration-200 ${
                  isExporting 
                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed dark:bg-gray-600 dark:text-gray-400' 
                    : 'bg-gradient-to-r from-green-600 to-green-700 text-white hover:from-green-700 hover:to-green-800 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5'
                }`}
              >
                {isExporting ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    Exporting...
                  </>
                ) : (
                  <>
                    <FileDown className="h-4 w-4" />
                    Export All Reports
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Notification System */}
        {notification && (
          <div className={`fixed top-4 right-4 z-50 p-4 rounded-lg shadow-lg border transition-all duration-300 transform ${
            notification.type === 'success' 
              ? 'bg-green-100 border-green-200 text-green-800 dark:bg-green-900/20 dark:border-green-800 dark:text-green-200'
              : 'bg-blue-100 border-blue-200 text-blue-800 dark:bg-blue-900/20 dark:border-blue-800 dark:text-blue-200'
          }`}>
            <div className="flex items-center gap-3">
              {notification.type === 'success' ? (
                <CheckCircle className="h-5 w-5" />
              ) : (
                <AlertCircle className="h-5 w-5" />
              )}
              <p className="font-medium">{notification.message}</p>
            </div>
          </div>
        )}

        {/* Reports Table */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full min-w-full">
              <thead className="bg-gray-50 dark:bg-gray-700/50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Report Name</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Type</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Date</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Status</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Generated By</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Size</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Downloads</th>
                  <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                {filteredReports.map((report) => (
                  <tr key={report.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors duration-200">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center gap-3">
                        {getReportTypeIcon(report.type)}
                        <div>
                          <p className="font-medium text-gray-900 dark:text-white">{report.title}</p>
                          <p className="text-sm text-gray-500 dark:text-gray-400">ID: #{report.id}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-gray-900 dark:text-white capitalize">{report.type.replace('-', ' ')}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-gray-900 dark:text-white">{report.date}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${getStatusColor(report.status)}`}>
                        {report.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-gray-900 dark:text-white">{report.generatedBy}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-gray-900 dark:text-white">{report.size}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="text-sm text-gray-900 dark:text-white">{report.downloads}</span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center gap-2">
                        <button 
                          onClick={() => console.log('View report:', report.title)}
                          className="p-2 text-blue-600 hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-900/20 rounded-lg transition-all duration-200 hover:scale-105"
                          title="View Report"
                        >
                          <Eye className="h-4 w-4" />
                        </button>
                        <button 
                          onClick={() => handleExportSingle(report)}
                          className="p-2 text-green-600 hover:bg-green-50 dark:text-green-400 dark:hover:bg-green-900/20 rounded-lg transition-all duration-200 hover:scale-105"
                          title="Export Report"
                        >
                          <FileDown className="h-4 w-4" />
                        </button>
                        <button 
                          onClick={() => console.log('Edit report:', report.title)}
                          className="p-2 text-yellow-600 hover:bg-yellow-50 dark:text-yellow-400 dark:hover:bg-yellow-900/20 rounded-lg transition-all duration-200 hover:scale-105"
                          title="Edit Report"
                        >
                          <Edit className="h-4 w-4" />
                        </button>
                        <button 
                          onClick={() => {
                            if (window.confirm(`Are you sure you want to delete "${report.title}"?`)) {
                              setReports(reports.filter(r => r.id !== report.id));
                              setNotification({ type: 'success', message: 'Report deleted successfully!' });
                              setTimeout(() => setNotification(null), 3000);
                            }
                          }}
                          className="p-2 text-red-600 hover:bg-red-50 dark:text-red-400 dark:hover:bg-red-900/20 rounded-lg transition-all duration-200 hover:scale-105"
                          title="Delete Report"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
