export const employeesData = [
  {
    id: 'EMP-001',
    name: 'Sarah Jenkins',
    email: 'sarah.j@company.com',
    avatar: 'https:
    department: 'Engineering',
    role: 'Senior Software Engineer',
    type: 'Full-time',
    dateJoined: '2021-03-15',
    status: 'Active',
    salary: 125000,
    leaveBalance: 12,
    performance: 92,
    lastLogin: '2026-03-14T08:30:00Z',
    manager: 'David Chen',
  },
  {
    id: 'EMP-002',
    name: 'Michael Chen',
    email: 'michael.c@company.com',
    avatar: 'https:
    department: 'Sales',
    role: 'Account Executive',
    type: 'Full-time',
    dateJoined: '2022-01-10',
    status: 'On Leave',
    salary: 85000,
    leaveBalance: 2,
    performance: 88,
    lastLogin: '2026-03-10T09:15:00Z',
    manager: 'Amanda Brooks',
  },
  {
    id: 'EMP-003',
    name: 'Emma Davis',
    email: 'emma.d@company.com',
    avatar: 'https:
    department: 'Marketing',
    role: 'Marketing Manager',
    type: 'Full-time',
    dateJoined: '2020-11-05',
    status: 'Active',
    salary: 95000,
    leaveBalance: 18,
    performance: 95,
    lastLogin: '2026-03-14T09:00:00Z',
    manager: 'Lisa Wong',
  },
  {
    id: 'EMP-004',
    name: 'David Smith',
    email: 'david.s@company.com',
    avatar: 'https:
    department: 'Engineering',
    role: 'Frontend Developer',
    type: 'Contract',
    dateJoined: '2023-08-20',
    status: 'Inactive',
    salary: 90000,
    leaveBalance: 0,
    performance: 75,
    lastLogin: '2026-02-28T17:45:00Z',
    manager: 'Sarah Jenkins',
  },
  {
    id: 'EMP-005',
    name: 'Alex Johnson',
    email: 'alex.j@company.com',
    avatar: 'https:
    department: 'HR',
    role: 'HR Specialist',
    type: 'Full-time',
    dateJoined: '2024-02-01',
    status: 'Probation',
    salary: 65000,
    leaveBalance: 5,
    performance: 80,
    lastLogin: '2026-03-14T08:45:00Z',
    manager: 'HR Admin',
  },
  {
    id: 'EMP-006',
    name: 'Olivia Martinez',
    email: 'olivia.m@company.com',
    avatar: 'https:
    department: 'Design',
    role: 'Product Designer',
    type: 'Part-time',
    dateJoined: '2022-06-12',
    status: 'Active',
    salary: 55000,
    leaveBalance: 8,
    performance: 90,
    lastLogin: '2026-03-13T10:20:00Z',
    manager: 'Tom Wilson',
  },
  {
    id: 'EMP-007',
    name: 'James Wilson',
    email: 'james.w@company.com',
    avatar: 'https:
    department: 'Engineering',
    role: 'DevOps Engineer',
    type: 'Full-time',
    dateJoined: '2021-09-01',
    status: 'Active',
    salary: 130000,
    leaveBalance: 15,
    performance: 94,
    lastLogin: '2026-03-14T07:30:00Z',
    manager: 'David Chen',
  },
];
